sudo: required
services:
  - docker

before_install:
  - docker build -t rofr95/git-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rofr95/git-docker npm run test # -e CI=true, otherwise travis waits indefinetly npm to exit