sudo: required
services:
  - docker

before_install:
  - docker build -t rofr95/git-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rofr95/git-docker npm run test # -e CI=true, otherwise travis waits indefinetly npm to exit


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-905418197231"
  bucket_path: "frontend"
  on:
    branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"